[package]
name = "async-oauth2"
authors = [
  "Alex Crichton <alex@alexcrichton.com>",
  "Florin Lipan <florinlipan@gmail.com>",
  "David A. Ramos <ramos@cs.stanford.edu>",
  "John-John Tedro <udoprog@tedro.se>"
]
version = "0.2.0"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/udoprog/async-oauth2"
edition = "2018"
readme = "README.md"

[lib]
name = "oauth2"

[dependencies]
base64 = "0.13.0"
rand = "0.8.2"
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.61"
sha2 = "0.9.2"
url = "2.2.0"
reqwest = "0.11.0"
thiserror = "1.0.23"
http = "0.2.3"
bytes = "1.0.1"

[dev-dependencies]
tokio = { version = "1.0.2", features = ["full"] }
