[package]
name = "async-oauth2"
authors = [
  "Alex Crichton <alex@alexcrichton.com>",
  "Florin Lipan <florinlipan@gmail.com>",
  "David A. Ramos <ramos@cs.stanford.edu>",
  "John-John Tedro <udoprog@tedro.se>"
]
version = "0.2.0"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/udoprog/async-oauth2"
edition = "2018"
readme = "README.md"

[lib]
name = "oauth2"

[dependencies]
base64 = "0.12.1"
rand = "0.7.3"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
sha2 = "0.8.1"
url = "2.1.1"
reqwest = "0.10.4"
thiserror = "1.0.16"
http = "0.2.1"
bytes = "0.5.4"

[dev-dependencies]
tokio = { version = "0.2.20", features = ["full"] }
