[package]
name = "async-oauth2-examples"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
publish = false

[lib]
name = "oauth2_examples"

[dependencies]
reqwest = "0.11.10"
tokio = { version = "1.17.0", features = ["full"] }
hyper = { version = "0.14.18", features = ["server", "http1"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_urlencoded = "0.7.1"
futures = "0.3.21"
tower-service = "0.3.1"
log = "0.4.16"
anyhow = "1.0.56"
clap = "3.1.6"
async-oauth2 = {path = ".."}
