[package]
name = "async-oauth2-examples"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
publish = false

[lib]
name = "oauth2_examples"

[dependencies]
reqwest = "0.11.0"
tokio = { version = "1.0.2", features = ["full"] }
hyper = { version = "0.14.2", features = ["server", "http1"] }
serde = { version = "1.0.119", features = ["derive"] }
serde_urlencoded = "0.7.0"
futures = "0.3.12"
tower-service = "0.3.0"
log = "0.4.13"
anyhow = "1.0.38"
clap = "2.33.3"
async-oauth2 = {path = ".."}
